### ISSUE TITLE
redis.exceptions.ResponseError: wrong number of arguments for 'rpush' command (Redis 2.4.6 + Windows 10)

### ISSUE THREAD

**Issue by ImCarrot** [ekzhu/datasketch#75] opened 2018-12-20 10:18 UTC
I am working with redis and LSH was going through your docs [here](https://ekzhu.github.io/datasketch/lsh.html). Below is my code

	from datasketch import MinHash, MinHashLSH

	set1 = {'minhash', 'is', 'a', 'probabilistic', 'data', 'structure', 'for', 'estimating', 'the', 'similarity', 'between',
			'datasets'}
	set2 = {'minhash', 'is', 'a', 'probability', 'data', 'structure', 'for', 'estimating', 'the', 'similarity', 'between',
			'documents'}
	set3 = {'minhash', 'is', 'probability', 'data', 'structure', 'for', 'estimating', 'the', 'similarity', 'between',
			'documents'}

	m1 = MinHash(num_perm=128)
	m2 = MinHash(num_perm=128)
	m3 = MinHash(num_perm=128)
	for d in set1:
		m1.update(d.encode('utf8'))
	for d in set2:
		m2.update(d.encode('utf8'))
	for d in set3:
		m3.update(d.encode('utf8'))

	# Create LSH index
	lsh = MinHashLSH(threshold=0.5, num_perm=128)
	lsh.insert("m2", m2)
	lsh.insert("m3", m3)
	result = lsh.query(m1)
	print("Approximate neighbours with Jaccard similarity > 0.5", result)

	lsh = MinHashLSH(
	   threshold=0.5, num_perm=128, storage_config={
		  'type': 'redis',
		  'redis': {'host': 'localhost', 'port': 6379}
	   })

	data_list = [("m1", m1), ("m2", m2), ("m3", m3)]

	with lsh.insertion_session() as session:
	   for key, minhash in data_list:
		  session.insert(key, minhash)

Below is what got printed to console:
     redis.exceptions.ResponseError: Command # 2 (RPUSH b'dvpuojwmwwe_keys\x80\x03K\x00.' 
     // between these there are a lot of lines that print out encoded stuff and then
    of pipeline caused error: wrong number of arguments for 'rpush' command

**Comment by ekzhu** [comment] 2018-12-22 09:11
@ae-foster Do you think this could be caused by version incompatibility?

**Comment by ekzhu** [comment] 2018-12-26 18:52
I tested with Redis 4.0.6 and 5.0.3 both ran without problem. What's your version?

**Comment by ImCarrot** [comment] 2018-12-26 19:00
@ekzhu I am running Redis server version 2.4.6 (26cdd13a:0) on my windows 10 machine. This is the latest version available. 
Please Note: When I use the same script with a Redis installed on Linux, it works just fine. Wondering if it got to do with Redis Windows 10 compatibility

**Comment by ae-foster** [comment] 2019-01-06 15:49
I would only guess a version issue. Could you use these newer versions? https://github.com/MicrosoftArchive/redis/releases

**Comment by ekzhu** [comment] 2019-09-05 19:46
Closing this now due to no follow up

**Closed by ekzhu** 2019-09-05 19:46 UTC
